//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class InterfaceContract : IInstance
{
	public virtual int GetIntValue()
	{
		throw new System.NotImplementedException();
	}

	public virtual void UseParam(int intValue)
	{
		throw new System.NotImplementedException();
	}

	public virtual int UseParamGetIntValue(int intValue)
	{
		throw new System.NotImplementedException();
	}

}

